### ISSUE TITLE
Add note on expected install time 

### ISSUE THREAD

**Issue by vsmart** [FiloSottile/homebrew-musl-cross#13]
Hi @FiloSottile! 

Thanks for maintaining this project 🙇‍♀. I got here by trying to  install a rust runtime for AWS Lambda from this [blog post](https://aws.amazon.com/de/blogs/opensource/rust-runtime-for-aws-lambda/). 

I ran:
>brew install filosottile/musl-cross/musl-cross

And it took maybe 30 minutes? I was confused and canceled and retried multiple time, thinking the process got stuck. 

When I saw this in the readme:

> (It takes a while, getting a cup of coffee won't do.)

I figure now this kind of install time is expected. 

My request: 

- Make the note in the Readme a bit clearer - can you suggest a ballpark of expected normal time? 
- Is it possible to add a warning about the install time to the brew output? 

Happy to submit a PR if  you have pointers on this two questions! thanks!

**Comment by brainstorm** [comment]
Wouldn't it make more sense to ship this as a pre-compiled bottle? [CI builds are failing because of this dependency](https://travis-ci.org/rust-bio/rust-htslib/jobs/648277321#L1375) :/

**Comment by haze** [comment]
@FiloSottile I noticed that gmake wasn't using a significant amount of cpu / resources during the compilation, is this intended? (when building llvm it uses all cores, and is way faster than this)

**Comment by brainstorm** [comment]
@haze Feel free to try out my fork over here, which does not require that long compile times (pre-bottled for OSX Catalina and High Sierra):

https://github.com/brainstorm/homebrew-musl-cross

**Comment by FiloSottile** [comment]
There is now a pre-built bottle for Catalina, built through GitHub actions making it likely I will keep updating it (but meaning there is no High Sierra bottle), and make is again running parallelized, so builds should be much faster (twice as fast on my machine), thanks @haze.

**Comment by brainstorm** [comment]
Fantastic! :)
