### ISSUE TITLE
Error: invalid option: --without-x86_64  Error: invalid option: --with-aarch64

### ISSUE THREAD

**Issue by goodforever** [FiloSottile/homebrew-musl-cross#17]
run on Mac Os Catalina version 10.15.3 
brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-aarch64
Error: invalid option: --without-x86_64

run
brew install FiloSottile/musl-cross/musl-cross  --with-aarch64
Error: invalid option: --with-aarch64

**Comment by FiloSottile** [comment]
That's weird, `brew install FiloSottile/musl-cross/musl-cross --without-x86_64 --with-aarch64` works for me on Catalina with the latest brew. Try uninstalling the formula if you already have it, and updating Homebrew?

**Comment by FiloSottile** [comment]
Timing out in waiting for info, feel free to open a new issue if you encounter this issue again.

**Comment by jiayihu** [comment]
I'm having the same issue, seems to be caused by install options being removed from brew 2.0 https://discourse.brew.sh/t/since-homebrew-2-0-0-install-params-always-give-invalid-option/4075/2

What is the alternative way to run the install? I'm not familiar with Ruby unfortunately, I guess it's something like cloning and running `musl-cross.rb`

**Comment by jiayihu** [comment]
Complimenti per la tempestività 😄 (Cancello poi il commento)

**Comment by symgryph** [comment]
I had the same issue, install w/o any options and then 'reinstall' with appropriate options

**Comment by brianstrauch** [comment]
```
brew install FiloSottile/musl-cross/musl-cross
brew reinstall musl-cross --with-aarch64
```

**Comment by FiloSottile** [comment]
I just tested

```
brew install filosottile/musl-cross/musl-cross --without-x86_64 --without-aarch64 --with-arm-hf
```

and it works with the latest Homebrew.

If folks are still running into this, please open a new issue with brew and macOS versions.
