### ISSUE TITLE
Add support for powerpc-linux-musl

### ISSUE THREAD

**Issue by k-matoski** [FiloSottile/homebrew-musl-cross#19]
Do you think you will be able to add support for powerpc-linux-musl?

**Comment by FiloSottile** [comment]
Yeah anything in here can be easily added.

https://github.com/richfelker/musl-cross-make#supported-targets

Can you test it and open a PR like #6?

**Comment by k-matoski** [comment]
I'm not able to create a PR, maybe I don't have access. Here is a patch that I tested locally.

[0001-Added-support-for-powerpc.patch.zip](https://github.com/FiloSottile/homebrew-musl-cross/files/4515959/0001-Added-support-for-powerpc.patch.zip)

**Comment by FiloSottile** [comment]
It should be possible to make a PR by forking, like any other GitHub project. I think it worked in the past. I'll apply the patch when I find time to sit down with it, but it would be quicker to review merge a PR. Thanks for testing it!
