### ISSUE TITLE
Downloading url 404，can you help me

### ISSUE THREAD

**Issue by xufanghui** [FiloSottile/homebrew-musl-cross#28]
brew install FiloSottile/musl-cross/musl-cross

Updating Homebrew...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
systemd
==> Updated Formulae
Updated 1 formula.

==> Installing musl-cross from filosottile/musl-cross
==> Downloading https://f001.backblazeb2.com/file/filippo-public//musl-cross-0.9.9_1.catalina.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "musl-cross"
Download failed: https://f001.backblazeb2.com/file/filippo-public//musl-cross-0.9.9_1.catalina.bottle.tar.gz

**Comment by FiloSottile** [comment]
The bottle was still being built and uploaded. Can you confirm it works now?

**Comment by DirectorX** [comment]
@FiloSottile 
> The bottle was still being built and uploaded. Can you confirm it works now?

still occurring....

**Comment by FiloSottile** [comment]
Should be actually fixed now, my bad!

**Comment by xufanghui** [comment]
Thanks. I'm happy!
