### ISSUE TITLE
GCC can’t find <linux/futex.h>

### ISSUE THREAD

**Issue by snej** [FiloSottile/homebrew-musl-cross#37]
I’m getting a build error “no such file” on `#include <linux/futex.h>`, down inside a library I use. And when I found the system headers down inside `/opt/homebrew/Cellar/musl-cross/0.9.9_1`, they don’t include such a header or even a `linux` subdirectory.

I know very little about Linux development, but I’m guessing this may have to do with musl vs. the default Linux library? In any case I have no idea how to work around this; it’s not even my code including this header, rather a 3rd party library.

**Comment by FiloSottile** [comment]
Unfortunately, I can't offer support for how to use the cross-compiler once installed, because the array of build systems and configurations is too diverse. Sorry!
