### ISSUE TITLE
Allow x86_64 with others

### ISSUE THREAD

**Issue by gwillem** [FiloSottile/homebrew-musl-cross#38]
If I run `brew install FiloSottile/musl-cross/musl-cross --with-aarch64 --with-x86_64`, it will not build the x86_64 chain, so I had to change `/opt/homebrew/Library/Taps/filosottile/homebrew-musl-cross/musl-cross.rb`:

```patch
-  option "without-x86_64", "Do not build cross-compilers targeting x86_64-linux-musl"
+  option "with-x86_64", "Build cross-compilers targeting x86_64-linux-musl"
```

PS. Thanks for this repo, it saved me a lot of time!

**Comment by FiloSottile** [comment]
x86_64 is installed by default, unless the `without-x86_64` option is selected.
