### ISSUE TITLE
Can not run on debian/Ubuntu

### ISSUE THREAD

**Issue by xiebruce** [FiloSottile/homebrew-musl-cross#42]
executable that build with the follow command can run on alpine(which is inside my docker container)
```bash
env CC=x86_64-linux-musl-gcc CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-w -s" -o "Hello2-Linux"
```

but can not run on Debian/Ubuntu, it returns error:
> bash: ./Hello2-Linux: No such file or directory

So how can I build executables that can run on debian/Ubuntu etc.

**Comment by FiloSottile** [comment]
Add `-extldflags=-static` to build a static binary that doesn't link dynamically against musl libc.
